# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm test

      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: npm install
      - run: npm run deploy

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/

      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
